services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Parkour2025
      POSTGRES_DB: dbmanualweb

    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/dbmanualweb

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://testuser:testpassword@db:5432/dbmanualweb
    ports:
      - "8000:8000"
    command: >
      sh -c "sleep 10 && python setup.py && uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
